FeedService/Controllers/FeedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FeedService.Controllers
{
    public class FeedController : Controller
    {
        // GET: Feed
        public ViewResult FeedChannels()
        {
            return View();
        }
        public ViewResult New()
        {
            return View();
        }
    }
}

FeedService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Feed Service", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Feed Channels", "FeedChannels", "Feed", new { area = "" }, null)</li>
                </ul>

                <ul id="logIn" class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                    <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                </ul>
                <ul id="loggedIn" class="nav navbar-nav navbar-right">
                    <li>
                        <a href="" id="UserName" class="text-muted"></a>
                    </li>
                    <li><a href="#" id="logOff">Log Off</a></li>
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Feed Service</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
    <script>
        $(document).ready(function () {
            if (sessionStorage.getItem("userName") != null || sessionStorage.getItem("userName") != undefined) {
                $("#UserName").text("Hello " + sessionStorage.getItem("userName") + "!");
                $("#logIn").hide();
            }
            else {
                $("#loggedIn").hide();
            }

            $("#logOff").click(function () {

                sessionStorage.removeItem("accessToken");
                sessionStorage.removeItem("userName");
                window.location.href = "/Account/Login";
                $("#UserName").empty();
                $("#loggedIn").hide();
                $("#logIn").show();
                
            });
        });
    </script>
</body>
</html>

FeedService/Views/Shared/_Login.cshtml
        <ul id ="loggedIn" class="nav navbar-nav navbar-right">
            <li>
                <span id="spanUserName" class="text-muted"></span>
            </li>
            <li><input id="logOff" type="button" class="btn" value="Log off" /></li>
        </ul>


    <ul id ="logIn" class="nav navbar-nav navbar-right">
        <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
        <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
    </ul>
}

@section scripts
{
    <script>
        $(document).ready(function () {
            if (sessionStorage.getItem("userName") != null || sessionStorage.getItem("userName") != undefined) {
                $("#spanUserName").text("Hello " + sessionStorage.getItem("userName") + "!");
                $("#logIn").hide();
            }
            else {
                $("#loggedIn").hide();
            }

            $("#logOff").click(function () {
                
                sessionStorage.removeItem("accessToken");
                window.location.href = "/Home";
            });
        });
    </script>


}